# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: budget_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget
    ports:
      - "5432:5432" # Local host port -> container port
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budget"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
